### ISSUE TITLE
Mangu alguses FPS dropid ja kimumine = fps increase?

### ISSUE THREAD

**Issue by SomeA-1** [plosee/Mustamae-seiklused#14]
tal on fucking 3080

![Image](https://user-images.githubusercontent.com/97263013/239628847-8c863616-8cd2-4be1-a6e9-c83f2b96f3f0.png)

no further comment necessary. top priority to fix

**Comment by SomeA-1** [comment]
eriti concerning on see et fps tuleb juurde kui kimub

**Comment by plosee** [comment]
alguses mingid spikeid on, peaks vaatam yle. muidu fps on 60 capped niiet sen whatever.

**Comment by plosee** [comment]
shadowid olid putsis, ei tea kimumise asja siiani, kuid ytleksin et sen fixed. orthogonal shadows ning default biasid peab panema
