### ISSUE TITLE
ai sitasti kooditud

### ISSUE THREAD

**Issue by SomeA-1** [plosee/Mustamae-seiklused#15]
põrkab ringi ja jälitab player kätt? (stabbimine lükkab vanameest nata tagasi)

**Comment by plosee** [comment]
tan normaalselt kooditud. ainuke probleemid on redundant objectid mida see kood vajab ning collision pask ning lykkamine.

**Comment by SomeA-1** [comment]
> tan normaalselt kooditud

ei.

**Comment by plosee** [comment]
koodi ise siis 😡😡

**Comment by SomeA-1** [comment]
ei
