### ISSUE TITLE
Kimu kadumisel puffimine jääb käima

### ISSUE THREAD

**Issue by SomeA-1** [plosee/Mustamae-seiklused#20]
assuming et kimu kadumine on intended behaviour

ja animation

**Comment by SomeA-1** [comment]
https://github.com/plosee/Mustamae-seiklused/assets/97263013/6d701bdc-da19-4fd1-b434-c114251afac3

**Comment by plosee** [comment]
see oli unintended animation issue, smokei tuleb valja aint ss kui puffimine lopetatakse. kimu kaob praegusel hetkel kui capacity value on 1, niiet bar naeb ka funky valja.
