### ISSUE TITLE
fullscreen button

### ISSUE THREAD

**Issue by SomeA-1** [plosee/Mustamae-seiklused#7]
väga annoying bug
pmst
ma tahan teha et if Window is Fullscreen
then fullscreen button is pressed down
but that code that "presses down" the fullscreen button also activates the signal to flip the window fullscreen value

**Comment by SomeA-1** [comment]
ma ei oska global vare lol
what the fuck is a singleton

**Comment by plosee** [comment]
tegin varem ju? lihtsalt pane mingi script autoloadima ja lao vare sisse, parast kasuta Global.* prefixi valitud var-i ees. idee mul oli naha kas sen fullscreen voi mitte ning muuta ikooni vastavalt, kuid maj taha teha kuna see softlockis mu arvtui pidevalt, niiet see on petsi too.

**Comment by SomeA-1** [comment]
html issue pmst kuna exe launchib fs
